--------------------------------------------------------
--  IMDB database creation script
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IMDB
--------------------------------------------------------

  CREATE TABLE "STUDENT"."IMDB" 
   (	"IMDB_RANKING" NUMBER(38,0), 
	"TITLE" VARCHAR2(512 BYTE), 
	"VOTE_AVERAGE" NUMBER(38,3), 
	"VOTE_COUNT" NUMBER(38,0), 
	"RELEASE_DATE" DATE, 
	"REVENUE" NUMBER(38,0), 
	"RUNTIME" NUMBER(38,0), 
	"BUDGET" NUMBER(38,0), 
	"IMDB_ID" VARCHAR2(26 BYTE), 
	"ORIGINAL_LANGUAGE" VARCHAR2(26 BYTE), 
	"OVERVIEW" VARCHAR2(4000 BYTE), 
	"TAGLINE" VARCHAR2(512 BYTE), 
	"GENRES" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;